name: Deploy Nuxt SSR App to Netcup

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js 20
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies with Yarn
        run: yarn install --frozen-lockfile

      - name: Build Nuxt SSR app
        run: yarn build

      - name: Deploy to Netcup via SSH
        env:
          DEPLOY_SSH_KEY: ${{ secrets.DEPLOY_SSH_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$DEPLOY_SSH_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 91.204.46.220 >> ~/.ssh/known_hosts

          # Upload everything needed to run app immediately
          scp -r \
            .nuxt \
            static \
            node_modules \
            nuxt.config.js \
            server.js \
            package.json \
            yarn.lock \
            hosting158062@91.204.46.220:/jonasvoglermusic.com/
